name: ci
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  cabal:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ["8.10.7", "9.0.2", "9.4", "9.6"]
        cabal: ["3.10.2.1"]
        os: [ubuntu-latest, macOS-latest]
    name: build and test (cabal)
    steps:
      - uses: actions/checkout@v2
      - name: Run Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
        id: setup-haskell
      - uses: actions/cache@v3
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ runner.os }}-v2-${{ matrix.ghc }}-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-v2-${{ matrix.ghc }}-
      - run: |
          cabal build all -fexamples
